---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-vm 
spec:
  results:
  - name: openshift-resources
    description: List of impacted openshift resources
  params:
  - name: FILE 
    description: FILENAME 
    type: string
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/bash
        oc create -f $(params.FILE) -o=jsonpath='{.kind}{"\t"}{.metadata.name}' | tee /tekton/results/openshift-resources
