---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sleep 
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/tags: cli
    tekton.dev/displayName: "sleep"

spec:
  params:
  - name: sleepSeconds
    type: string 
    description: Number of seconds to wait before checking for resource readiness
    default: "0"
  steps:
  - name: sleepy-time 
    image: registry.access.redhat.com/ubi8/ubi
    script: |
      #!/bin/bash
      echo 'Sleepy time: $(params.sleepSeconds)'
      sleep $(params.sleepSeconds)
      echo 'Time to wake up!'
