apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    app: rhel7-base
    vm.kubevirt.io/template: rhel7-server-small-v0.11.3
    vm.kubevirt.io/template.revision: "1"
    vm.kubevirt.io/template.version: devel
  name: rhel7-base
  generateName: rhel7-base-
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: rhel7-base
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - name: rootdisk
        persistentVolumeClaim:
          claimName: rhel7-vm-disk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: redhat
            chpasswd: { expire: False }
        name: cloudinitdisk
