apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rhtr-dns-ut 
spec:
  tasks:
     - name: create-id
       taskRef:
         name: create-id
     - name: create-ns
       taskRef:
         name: openshift-client 
       params:
         - name: ARGS
           value:
             - new-project
             - cnv-tekton-$(tasks.create-id.results.pipeline-id)
#     - name: lint-dns
#       taskRef:
#         name: ansible-lint
#       params:
#         - name: ARGS
#           value:
     - name: create-vmi
       taskRef:
         name: openshift-client
       params:
         - name: ARGS
           value: ["apply","-f","https://raw.githubusercontent.com/tylerauerbeck/rhtr-2020-infra-cicd/main/cnv/fedora32.yaml"]
     - name: expose-vmi-ssh
       taskRef:
         name: virtctl
       params:
         - params: ARGS
           value: ["expose","vmi-fedora-1"]
     - name: wait-for-vm
       taskRef:
         name: sleep
       params:
         - name: sleepSeconds
           value: 200
#     - name: run-ansible 

      
